status = [
  "formatting",
  "clippy (daemon)",
  "clippy (rocket-basicauth)",
  "clippy (rust-embed-rocket)",
  "clippy (taker)",
  "clippy (maker)",
  "clippy (shared-bin)",
  "clippy (daemon-tests)",
  "clippy (tokio-tasks)",
  "clippy (xtras)",
  "clippy (bdk-ext)",
  "clippy (model)",
  "clippy (xtra-bitmex-price-feed)",
  "lint-commits",
  "frontend (maker)",
  "frontend (taker)",
  "test_daemons (ubuntu-latest)",
  "test_daemons (macos-latest)",
  "test_daemons_release_mode (ubuntu-latest)",
  "test_daemons_release_mode (macos-latest)",
  "daemons_arm_build",
]
