[workspace]
members = [
  "daemon",
  "rocket-basicauth",
  "rust-embed-rocket",
  "taker",
  "maker",
  "shared-bin",
  "daemon-tests",
  "tokio-tasks",
  "xtras",
  "xtra-bitmex-price-feed",
  "bdk-ext",
  "model",
]
resolver = "2"

[patch.crates-io]
xtra = { git = "https://github.com/comit-network/xtra" } # We need to use unreleased patches.
maia = { git = "https://github.com/comit-network/maia" } # Unreleased
xtra_productivity = { git = "https://github.com/comit-network/xtra-productivity" } # Unreleased
sqlx = { git = "https://github.com/comit-network/sqlx", branch = "sqlite-unlock-notify" } # https://github.com/itchysats/itchysats/issues/1168
