[package]
name = "bdk-ext"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bdk = { version = "0.17", default-features = false }
rand = "0.6"
secp256k1 = { version = "0.20", features = ["rand", "global-context-less-secure"] }
