[package]
name = "daemon"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1.52"
atty = "0.2"
bdk = { version = "0.15", default-features = false, features = ["electrum"] }
bytes = "1"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "3.0.1", features = ["derive"] }
derive_more = { version = "0.99.17", default-features = false, features = ["display"] }
futures = { version = "0.3", default-features = false }
hex = "0.4"
hkdf = "0.12"
http-api-problem = { version = "0.51.0", features = ["rocket"] }
itertools = "0.10"
maia = "0.1.0"
nalgebra = { version = "0.30", default-features = false, features = ["std"] }
ndarray = "0.15.4"
ndarray_einsum_beta = "0.7.0"
num = "0.4.0"
rand = "0.6"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls-webpki-roots"] }
rocket = { version = "0.5.0-rc.1", features = ["json"] }
rocket-basicauth = { version = "2", default-features = false }
rust-embed = "6.3"
rust_decimal = "1.19"
rust_decimal_macros = "1.19"
semver = { version = "1.0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_plain = "1"
serde_with = { version = "1", features = ["macros"] }
sha2 = "0.10"
snow = "0.8"
sqlx = { version = "0.5", features = ["offline", "sqlite", "uuid", "runtime-tokio-rustls"] }
thiserror = "1"
time = { version = "0.3", features = ["serde"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "net"] }
tokio-tungstenite = { version = "0.15", features = ["rustls-tls"] }
tokio-util = { version = "0.6", features = ["codec"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.2", default-features = false, features = ["fmt", "ansi", "env-filter", "chrono", "tracing-log", "json"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
x25519-dalek = { version = "1.1" }
xtra = { version = "0.6" }
xtra_productivity = { version = "0.1.0" }

[[bin]]
name = "taker"
path = "src/taker.rs"

[[bin]]
name = "maker"
path = "src/maker.rs"

[dev-dependencies]
mockall = "0.11.0"
mockall_derive = "0.11.0"
pretty_assertions = "1"
serde_test = "1"
time = { version = "0.3", features = ["std"] }

[build-dependencies]
vergen = "6"
anyhow = "1"
