[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[alias]
dev-maker = "run --bin maker -- testnet"
dev-taker = "run --bin taker -- --maker localhost:9999 --maker-id 10d4ba2ac3f7a22da4009d813ff1bc3f404dfe2cc93a32bedf1512aa9951c95e --maker-peer-id 12D3KooWDjzHna3pNi1Bt1DoRfrpsBREykJKXDRDxXvhJNAdDZEk testnet" # Maker ID matches seed found in `testnet/maker_seed`

# Inspired by https://github.com/EmbarkStudios/rust-ecosystem/pull/68.
[build]
rustflags = [
  "-Wclippy::disallowed_methods",
  "-Wclippy::dbg_macro",
  "-Wclippy::print_stderr",
  "-Wclippy::print_stdout",
  "-Wunused-import-braces",
  "-Wmissing-copy-implementations",
  "-Wunused-import-braces",
  "-Wunused-qualifications",
]
