[package]
name = "xtra-bitmex-price-feed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-trait = "0.1"
futures = "0.3"
rust_decimal = { version = "1", features = ["serde-with-float"] }
rust_decimal_macros = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
time = { version = "0.3", features = ["serde-well-known"] }
tokio = "1"
tokio-tasks = { path = "../tokio-tasks" }
tokio-tungstenite = { version = "0.15", features = ["rustls-tls"] }
tracing = "0.1"
xtra = "0.6"
xtra_productivity = { version = "0.1.0" }
xtras = { path = "../xtras" }
