[package]
name = "vergen-version"
version = "0.1.0"
edition = "2021"
description = "Expose workspace version with git hash using vergen"

[dependencies]

[build-dependencies]
anyhow = "1"
vergen = "7"
