name: Add new pull requests to project board

on:
  pull_request:
    types:
      - opened

jobs:
  add_issue_to_project:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api graphql -f query='mutation($project:ID!, $issue:ID!) { addProjectNextItem(input: {projectId: $project, contentId: $issue}) { projectNextItem { id }  } }' -f project=${{ secrets.PROJECT_BOARD_ID }} -f issue=${{ github.event.pull_request.node_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.ITCHY_PROJECT_AUTOMATION_TOKEN }}
