on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

name: bloat

jobs:
  cargo_bloat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run cargo bloat
        uses: orf/cargo-bloat-action@v1
        with:
          token: ${{ secrets.ITCHY_GITHUB_TOKEN }}
          exclude_packages: "daemon,rocket-basicauth,rust-embed-rocket,shared-bin, daemon-tests, tokio-extras, otel-tests, otel-tests-macro, xtras, xtra-bitmex-price-feed, bdk-ext, model, btsieve, bitmex-stream, xtra-libp2p, xtra-libp2p-ping, xtra-libp2p-offer, xtra-libp2p-rollover, sqlite-db, quiet-spans, vergen-version"
