name: CI

on:
  pull_request:
  push:
    branches:
      - 'staging'
      - 'master'

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: dprint/check@v2.0

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: stable
          components: clippy
      - uses: Swatinem/rust-cache@v1.3.0
      - run: cargo clippy --workspace --all-targets -- -D warnings

  check_maker_frontend:
    defaults:
      run:
        working-directory: maker-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          cache-dependency-path: maker-frontend/yarn.lock
      - run: yarn install
      - run: yarn run eslint
      - run: yarn run tsc

  check_taker_frontend:
    defaults:
      run:
        working-directory: taker-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          cache-dependency-path: taker-frontend/yarn.lock
      - run: yarn install
      - run: yarn run eslint
      - run: yarn run tsc

  build_and_test_maker_frontend:
    defaults:
      run:
        working-directory: maker-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          cache-dependency-path: maker-frontend/yarn.lock
      - run: yarn install
      - run: yarn test
      - run: yarn build

  build_and_test_taker_frontend:
    defaults:
      run:
        working-directory: taker-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          cache-dependency-path: taker-frontend/yarn.lock
      - run: yarn install
      - run: yarn build

  test_daemons:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup rust toolchain
        run: rustup show
      - uses: Swatinem/rust-cache@v1.3.0
      - run: cargo build --features expensive_tests --bins --tests
      - run: cargo test --workspace --features expensive_tests
      - name: Smoke test ${{ matrix.os }} binary
        shell: bash
        run: |
          mkdir -p /tmp/maker/testnet
          cp -r daemon/util/testnet_seeds/maker_seed /tmp/maker/testnet/maker_seed
          target/debug/maker --data-dir=/tmp/maker testnet &
          sleep 10s # Wait for maker to start\

          # The maker-id is generated from the makers seed found in daemon/util/testnet_seeds/maker_seed
          target/debug/taker --data-dir=/tmp/taker --generate-seed --maker-id 10d4ba2ac3f7a22da4009d813ff1bc3f404dfe2cc93a32bedf1512aa9951c95e testnet &
          sleep 10s # Wait for taker to start

          curl --fail http://localhost:8000/api/alive
          curl --fail http://localhost:8001/api/alive
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: maker-and-taker-binaries-${{ matrix.os }}
          path: |
            target/debug/maker
            target/debug/taker

  daemons_arm_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: armv7-unknown-linux-gnueabihf
          - target: aarch64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup rust toolchain
        run: rustup show
      - uses: Swatinem/rust-cache@v1.3.0
      - name: Install compiler for armhf arch
        if: matrix.target == 'armv7-unknown-linux-gnueabihf'
        run: |
          sudo apt-get update
          sudo apt-get install gcc-arm-linux-gnueabihf

      - name: Install compiler for aarch64 arch
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install gcc-aarch64-linux-gnu
      - run: cargo build --target=${{ matrix.target }} --bins
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: maker-and-taker-binaries-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/debug/maker
            target/${{ matrix.target }}/debug/taker
